In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
finance = pd.read_csv("Sentiment.csv")

In [3]:
tech = pd.read_csv("Sentiment1.csv") 

In [4]:
health = pd.read_csv("Sentiment2.csv")

In [5]:
import pandas_datareader.data as web

import datetime

start = datetime.datetime(2010, 1, 1)

end = datetime.datetime(2015, 5, 5)

apple = web.DataReader("AAPL", 'yahoo', start, end)

In [150]:
apple.head()

High        Low       Open      Close       Volume  Adj Close
Date                                                                          
2009-12-31  30.478571  30.080000  30.447144  30.104286   88102700.0  26.061205
2010-01-04  30.642857  30.340000  30.490000  30.572857  123432400.0  26.466835
2010-01-05  30.798571  30.464285  30.657143  30.625713  150476200.0  26.512596
2010-01-06  30.747143  30.107143  30.625713  30.138571  138040000.0  26.090879
2010-01-07  30.285715  29.864286  30.250000  30.082857  119282800.0  26.042646

In [25]:
apple_yearly = apple.resample('AS').ffill().pct_change()

In [39]:
apple_yearly.dropna()

High       Low      Open     Close    Volume  Adj Close
Date                                                                   
2011-01-01  0.516194  0.525978  0.515272  0.530679 -0.450902   0.530679
2012-01-01  0.255966  0.255765  0.249450  0.255580 -0.071553   0.255580
2013-01-01  0.317810  0.261493  0.265223  0.314000  2.670739   0.325669
2014-01-01  0.048338  0.088409  0.085480  0.054212 -0.661733   0.080695
2015-01-01  0.410900  0.392545  0.425086  0.377241 -0.257619   0.406225

In [29]:
apple_y = apple.resample('AS').std()/apple.resample('AS').mean()

In [40]:
apple_y.dropna()[1:]

High       Low      Open     Close    Volume  Adj Close
Date                                                                   
2011-01-01  0.071718  0.070935  0.071334  0.071219  0.444149   0.071219
2012-01-01  0.116345  0.116878  0.117108  0.116269  0.439147   0.116819
2013-01-01  0.093276  0.096260  0.095114  0.094974  0.435597   0.099977
2014-01-01  0.145759  0.144238  0.145115  0.144923  0.465794   0.150794
2015-01-01  0.059233  0.061772  0.060044  0.060810  0.367368   0.062287

In [52]:
df = pd.DataFrame()

In [53]:
df['category'] = tech[3:8].iloc[::-1]['sentiment']

In [54]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
  

df['category']= label_encoder.fit_transform(df['category']) 

In [16]:
from sklearn.linear_model import LinearRegression
l = LinearRegression()

In [59]:
tech.head(10)

Unnamed: 0        date ticker     sentiment
0           0  2018-01-01   AAPL   uncertainty
1           1  2017-01-01   AAPL  constraining
2           2  2016-01-01   AAPL   uncertainty
3           3  2015-01-01   AAPL   uncertainty
4           4  2014-01-01   AAPL   uncertainty
5           5  2013-01-01   AAPL  constraining
6           6  2012-01-01   AAPL     litigious
7           7  2011-01-01   AAPL      negative
8           8  2010-01-01   AAPL      negative
9           9  2009-01-01   AAPL   uncertainty

In [78]:
te = tech[tech['ticker'] == 'AAPL']

In [85]:
te['Date'] = pd.to_datetime(te['Date'])

c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [83]:
te['Date'] = te['date']
te.drop('date',axis=1,inplace=True)

c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [58]:
df

category
7         2
6         1
5         0
4         3
3         3

In [57]:
l.fit(df,apple_yearly['Adj Close'].dropna())

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [63]:
l.predict(df[4:])

array([0.30208232])

In [14]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 

In [180]:
st = pd.DataFrame()

In [45]:
stock(finance)

AIG
              return  volatility
Date                            
2011-01-01  0.921948    6.297750
2012-01-01 -0.514589    2.669089
2013-01-01  0.521552    4.331880
2014-01-01  0.452043    2.187779
2015-01-01  0.107389    2.080709
[0.25907489]
[3.84485708]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


AXP
              return  volatility
Date                            
2011-01-01  0.078372    2.361213
2012-01-01  0.116577    2.544748
2013-01-01  0.235847    7.293519
2014-01-01  0.598358    2.861970
2015-01-01  0.036627    3.429058
[0.20748329]
[2.79924713]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


BAC
              return  volatility
Date                            
2011-01-01 -0.111573    2.972826
2012-01-01 -0.581215    1.057798
2013-01-01  1.098256    1.194080
2014-01-01  0.345106    0.791150
2015-01-01  0.157352    0.464242
[-0.41968338]
[2.43451386]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


C
              return  volatility
Date                            
2011-01-01  0.429003    7.669942
2012-01-01 -0.443294    3.634446
2013-01-01  0.505512    3.161402
2014-01-01  0.318358    2.396856
2015-01-01  0.039218    1.832370
[0.16975942]
[3.73900305]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


WFC
              return  volatility
Date                            
2011-01-01  0.156227    2.190160
2012-01-01 -0.095360    1.419571
2013-01-01  0.273463    2.862339
2014-01-01  0.367148    2.551478
2015-01-01  0.241081    1.123585
[0.04394754]
[4.52049028]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


BRK
              return  volatility
Date                            
2011-01-01  0.047619    1.193126
2012-01-01 -0.713905    0.344053
2013-01-01 -0.029838    0.008475
2014-01-01 -0.844444    0.483496
2015-01-01  7.714286    0.493533
[2.53384263]
[0.61152566]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


MS
              return  volatility
Date                            
2011-01-01 -0.073892    4.666970
2012-01-01 -0.439040    1.802475
2013-01-01  0.283330    2.817070
2014-01-01  0.653442    2.154536
2015-01-01  0.250779    0.871201
[0.13492379]
[2.46245033]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


GS
              return  volatility
Date                            
2011-01-01  0.005424   23.286107
2012-01-01 -0.455977    9.656772
2013-01-01  0.433920    9.007570
2014-01-01  0.407936   10.863286
2015-01-01  0.107853    6.542231
[0.10463055]
[11.53308459]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


JPM
              return  volatility
Date                            
2011-01-01  0.023074    4.286403
2012-01-01 -0.199180    2.903300
2013-01-01  0.361806    3.017538
2014-01-01  0.367334    2.068336
2015-01-01  0.098828    2.233469
[0.15719688]
[2.55566067]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


MA
              return  volatility
Date                            
2011-01-01 -0.101463    4.054059
2012-01-01  0.700396    3.531312
2013-01-01  0.358653    9.019058
2014-01-01  0.763660    4.423102
2015-01-01  0.049844    2.976643
[0.39071887]
[5.4729344]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [6]:
rt = pd.DataFrame()

In [44]:
returns = []
volatility = []

In [24]:
def stock(frame):
    ticker = frame['ticker'].unique()
    for s in ticker:
        rt['ticker'] = s 
        data = web.DataReader(s, 'yahoo', start, end)
        #print(st)
        print(s)
        rt['return'] = data.resample('AS').ffill().pct_change()['Adj Close']
        rt['volatility'] = data.resample('AS').std()['Adj Close']
        portfolio(frame,rt,s)

In [40]:
def portfolio(dfr,fr,tick):
        dfr['sentiment']= label_encoder.fit_transform(dfr['sentiment'])
        fr.drop('ticker',axis=1,inplace=True)
        print(fr)
        fr.dropna(inplace=True)
        dfr = dfr[dfr['ticker'] == tick]
        dfr.reset_index(inplace=True)
        dfr.drop('index',axis=1,inplace=True)
        dfr['date'] = pd.to_datetime(dfr['date'])
        #t = dfr.join(fr,how="right",on=dfr['date'])
        b = np.zeros(shape = (5,1))
        a = np.zeros(shape = (1,1))
        for i in range(len(dfr['sentiment'])):
            #print(dfr.loc[i,'date'])
            if dfr.loc[i,'date'].year == 2015 :
                a[0,0] = dfr.loc[i,'sentiment']
                b[0,0] = dfr.loc[i+5,'sentiment']
                b[1,0] = dfr.loc[i+4,'sentiment']
                b[2,0] = dfr.loc[i+3,'sentiment']
                b[3,0] = dfr.loc[i+2,'sentiment']
                b[4,0] = dfr.loc[i+1,'sentiment']
                #b = pd.DataFrame(b)
                #print(b)
                #print(fr['return'])
                l.fit(b,fr['return'])
                pred = l.predict(a)
                print(pred)
                returns.append(pred)
                l.fit(b,fr['volatility'])
                pre = l.predict(a)
                print(pre)
                volatility.append(pre)

In [18]:
tech = tech[tech['ticker'] != 'EMC']

In [46]:
stock(tech[tech['ticker'] != 'ALTR'])

AAPL
              return  volatility
Date                            
2011-01-01  0.530679    3.206030
2012-01-01  0.255580    8.342429
2013-01-01  0.325669    5.975804
2014-01-01  0.080695   12.614347
2015-01-01  0.406225    7.003729
[0.48105972]
[4.98632494]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

AMAT
              return  volatility
Date                            
2011-01-01  0.030583    1.569259
2012-01-01 -0.218704    0.597244
2013-01-01  0.101913    1.652769
2014-01-01  0.585533    2.007906
2015-01-01  0.436955    1.266696
[0.18073709]
[1.35253485]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

CSCO
              return  volatility
Date                            
2011-01-01 -0.154971    1.347524
2012-01-01 -0.096171    1.130270
2013-01-01  0.116055    1.479448
2014-01-01  0.167266    1.579929
2015-01-01  0.279758    0.771246
[0.06473009]
[0.94719315]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

HPQ
              return  volatility
Date                            
2011-01-01 -0.169614    2.402666
2012-01-01 -0.367591    1.493819
2013-01-01 -0.411434    1.264819
2014-01-01  1.070138    1.281579
2015-01-01  0.491918    1.062709
[0.02780823]
[1.43182003]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

IBM
              return  volatility
Date                            
2011-01-01  0.142612    8.385582
2012-01-01  0.274120    5.347347
2013-01-01  0.059249    7.870369
2014-01-01 -0.001776    8.410860
2015-01-01 -0.123871    4.286460
[0.08259164]
[6.72417797]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

INTC
              return  volatility
Date                            
2011-01-01  0.062695    1.269374
2012-01-01  0.193964    1.935417
2013-01-01 -0.120146    1.267955
2014-01-01  0.309201    3.964329
2015-01-01  0.442240    1.546546
[0.27911303]
[1.23965804]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

MSFT
              return  volatility
Date                            
2011-01-01 -0.065246    0.903242
2012-01-01 -0.045157    1.238880
2013-01-01  0.057989    3.167455
2014-01-01  0.442980    3.721763
2015-01-01  0.275646    2.134804
[0.02919563]
[3.05310542]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

MU
              return  volatility
Date                            
2011-01-01 -0.240530    2.260361
2012-01-01 -0.215711    0.942952
2013-01-01  0.007949    4.463836
2014-01-01  2.430599    4.372111
2015-01-01  0.609655    1.851068
[-0.0831505]
[4.16848091]


c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\pandas\core\frame.py:4097: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\users\kiit\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

## Optimization

In [47]:
volatility

[array([3.84485708]),
 array([2.79924713]),
 array([2.43451386]),
 array([3.73900305]),
 array([4.52049028]),
 array([0.61152566]),
 array([2.46245033]),
 array([11.53308459]),
 array([2.55566067]),
 array([5.4729344]),
 array([4.98632494]),
 array([1.35253485]),
 array([0.94719315]),
 array([1.43182003]),
 array([6.72417797]),
 array([1.23965804]),
 array([3.05310542]),
 array([4.16848091])]

In [48]:
num_ports = 15000

all_weights = np.zeros((num_ports,18))
ret_arr = np.zeros(num_ports)
vol_arr = np.zeros(num_ports)
sharpe_arr = np.zeros(num_ports)

for ind in range(num_ports):

    # Create Random Weights
    weights = np.array(np.random.random(18))

    # Rebalance Weights
    weights = weights / np.sum(weights)
    
    # Save Weights
    all_weights[ind,:] = weights

    for i in range(18):
        ret_arr[ind] = ret_arr[ind] + weights[i]*float(returns[i])
        vol_arr[ind] = vol_arr[ind] + weights[i]*float(volatility[i])

    # Sharpe Ratio
    sharpe_arr[ind] = ret_arr[ind]/vol_arr[ind]

In [49]:
sharpe_arr

array([0.09223084, 0.0604778 , 0.04836515, ..., 0.09697466, 0.07506356,
       0.07815735])

In [50]:
ret_arr

array([0.26115816, 0.20270296, 0.1657388 , ..., 0.34443896, 0.24791201,
       0.29466697])

In [51]:
vol_arr

array([2.83157081, 3.35169201, 3.42682319, ..., 3.55184514, 3.30269436,
       3.77017587])

In [52]:
sharpe_arr.max()

0.20510905640370478

In [53]:
sharpe_arr.argmax()

12484

In [57]:
all_weights[12484]

array([0.11251677, 0.00937105, 0.00894239, 0.00525869, 0.1053034 ,
       0.17950953, 0.00275714, 0.03290383, 0.00325209, 0.0327263 ,
       0.02087943, 0.16724595, 0.08997681, 0.01915364, 0.01875412,
       0.06818934, 0.0530442 , 0.07021533])

In [58]:
ret_arr[12484]

0.5677441385554417

In [55]:
#thus optimized portfolio weights have been found